"""
Ties every other module into one coherent turn of conversation: this is where the pieces built and tested standalone across the rest of 
the codebase actually get wired together and run for real.

WHAT PROBLEM THIS FILE SOLVES: Every layer built so far (the lexicon, the grammar, compositional semantics, figurative repair, the
world model, discourse tracking) works correctly on its own: each has its own tests proving that. But a working system isn't just a pile of correct, 
independent pieces; it's those pieces actually calling each other in the right order, on real data, with each one's output feeding the next one's
input. That's this file's entire job, and only this file's job: no new linguistic mechanism gets invented here, only orchestration of mechanisms that 
already exist.

WHAT ONE TURN ACTUALLY DOES, IN ORDER:
    1. Advance the world model's turn clock (so this turn's events get the right relative timing).

    2. Parse the utterance, keeping both the LogicalForm and the derivation tree.

    3. Register any newly-mentioned nouns as discourse referents, using the ORIGINAL (pre-resolution) arguments: a pronoun is never itself a new lexicon noun, 
    so this step naturally never registers a pronoun as if it were a fresh entity.

    4. Resolve every pronoun argument: try cataphora first (forward reference within this sentence, licensed only by Principle C), then fall back to ordinary backward 
    resolution against the world model's active referents, honoring whatever gender/number/animacy the specific pronoun carries.

    5. Check every presupposition trigger word in the utterance against what's already known, accommodating (assuming, and recording) anything genuinely new rather than 
    failing on it.

    6. Disambiguate any polysemous word against its sentence-mates' selectional constraints.

    7. Classify the utterance's speech act, and detect focus if a focus particle is present.

    8. Compile and evaluate truth via SemanticCompiler; if the predicate was idiom-tagged during parsing, look up and attach its real (figurative.py) meaning to the payload.
    
    9. Record the utterance as an event on the world model's episodic timeline.
    
    10. Collect any scalar implicatures generated by the words actually used.

WHAT THIS FILE DOES NOT DO: It doesn't invoke a language model anywhere: that's interface/neural_bridge.py, not built yet, and nothing here reaches for it as a silent fallback. 
It also doesn't paper over gaps in what the grammar can parse: cataphora resolution, presupposition triggers, and several other mechanisms wired in here will only ever fire on 
the sentence shapes core/parser.py can actually produce today: see the architecture plan's "known partial implementations" section for the current honest list of what that does 
and doesn't cover.
"""

from typing import Dict, Any, List

from core.lexicon import LexiconManager
from core.parser import ChartParser, get_pronoun_features
from core.world_model import WorldModel
from core.world_model import get_presupposition_trigger as _get_presupposition_trigger
from core.semantics import SemanticCompiler
from core.figurative import rewrite_idiom
from core.discourse import (
    classify_speech_act,
    resolve_pronoun_with_agreement,
    attempt_cataphora_resolution,
    find_pronoun_and_name_leaves,
    detect_focus,
    accommodate_presupposition,
    generate_scalar_implicature,
)

_PRONOUN_TOKENS = {"it", "he", "him", "she", "her", "they", "them"}

class DEMESPipeline:
    """
    Coordinates the full symbolic NLU pipeline for one turn of conversation.
    """
    def __init__(self, lexicon_path: str = "data/lexicon.json"):
        self.lexicon = LexiconManager(store_path=lexicon_path)
        self.world_model = WorldModel()
        self.parser = ChartParser(self.lexicon)
        self.compiler = SemanticCompiler(self.world_model, self.lexicon)

    def process_utterance(self, raw_text: str) -> Dict[str, Any]:
        """
        Runs one complete turn: parse, resolve, accommodate, disambiguate, classify, evaluate, and record.
        """
        self.world_model.advance_turn()
        tokens = self.parser.tokenize(raw_text)

        logical_form, derivation_tree = self.parser.parse_with_derivation(raw_text)

        if logical_form:
            self._register_noun_arguments(logical_form)
            self._resolve_pronoun_arguments(logical_form, derivation_tree)

        accommodated_presuppositions = self._check_presuppositions(tokens, logical_form)
        word_senses = self._disambiguate_utterance(tokens)
        speech_act = classify_speech_act(logical_form, raw_text)
        focused_constituent = detect_focus(tokens)
        implicatures = [imp for imp in (generate_scalar_implicature(t) for t in tokens) if imp]

        semantic_payload = self.compiler.compile_and_evaluate(logical_form)
        self._attach_idiom_meaning(logical_form, semantic_payload)

        if logical_form:
            self.world_model.record_event(logical_form.predicate, roles={}, tense=logical_form.tense)

        return {
            "raw_text": raw_text,
            "logical_form": logical_form,
            "semantics": semantic_payload,
            "speech_act": speech_act.value,
            "word_senses": word_senses,
            "implicatures": implicatures,
            "accommodated_presuppositions": accommodated_presuppositions,
            "focus": focused_constituent,
        }

    # Discourse referents and pronoun resolution.
    def _register_noun_arguments(self, logical_form) -> None:
        """
        Registers any argument that is itself a lexicon noun as a fresh discourse referent, using the arguments 
        exactly as the parser produced them: a bare pronoun token like "it" isn't a lexicon entry at all (see core/parser.py's PRONOUNS table), 
        so this step naturally never mistakes a pronoun for a new noun mention.
        """
        for argument in logical_form.arguments:
            entry = self.lexicon.get_word_definition(str(argument))
            if entry and entry.get("category") == "noun":
                self.world_model.register_referent(str(argument), "noun", properties=[logical_form.predicate.lower()])

    def _resolve_pronoun_arguments(self, logical_form, derivation_tree) -> None:
        """
        Resolves every pronoun argument in place. Cataphora (a pronoun referring to a name later in the same sentence) is tried first against 
        the retained derivation tree, since it's the more specific, structurally-licensed case; ordinary backward resolution against the world
        model's active referents is the fallback for everything else.
        """
        if derivation_tree is not None:
            pronoun_leaves, name_leaves = find_pronoun_and_name_leaves(derivation_tree, _PRONOUN_TOKENS)
            for pronoun_leaf in pronoun_leaves:
                later_names = [leaf for leaf in name_leaves if leaf.span[0] > pronoun_leaf.span[0]]
                resolved = attempt_cataphora_resolution(derivation_tree, pronoun_leaf, later_names)
                
                if resolved is not None:
                    logical_form.arguments = [
                        resolved.token if argument == pronoun_leaf.token else argument
                        for argument in logical_form.arguments
                    ]

        logical_form.arguments = [
            self._resolve_single_pronoun(str(argument)) if str(argument).lower() in _PRONOUN_TOKENS else argument
            for argument in logical_form.arguments
        ]

    def _resolve_single_pronoun(self, pronoun_text: str) -> str:
        features = get_pronoun_features(pronoun_text) or {}
        referent = resolve_pronoun_with_agreement(
            self.world_model,
            required_gender = features.get("gender"),
            required_number = features.get("number"),
            required_animate = features.get("animate"),
        )
        return referent.name if referent else pronoun_text

    # Presupposition accommodation.
    def _check_presuppositions(self, tokens: List[str], logical_form) -> List[str]:
        """
        Checks every presupposition-trigger word actually used (matched by lemma, so "stopped" and "stop" both trigger the same check) against what's 
        already known, accommodating anything genuinely new. Returns the list of trigger words that were newly accommodated this turn.
        """
        if not logical_form or not logical_form.arguments:
            return []

        subject = str(logical_form.arguments[0])
        accommodated = []
        for token in tokens:
            lemma = self.lexicon.lemmatize(token) or token

            if _get_presupposition_trigger(lemma) is not None:
                if accommodate_presupposition(self.world_model, lemma, subject):
                    accommodated.append(lemma)
        
        return accommodated

    # Word-sense disambiguation.
    def _disambiguate_utterance(self, tokens: List[str]) -> Dict[str, str]:
        word_senses = {}
        for token in tokens:
            word_def = self.lexicon.get_word_definition(token)

            if word_def and len(word_def.get("senses", [])) > 1:
                argument_types = self._collect_type_tags(tokens, exclude_token = token)
                word_senses[token] = self.lexicon.disambiguate_sense(token, argument_types)

        return word_senses

    def _collect_type_tags(self, tokens: List[str], exclude_token: str) -> List[str]:
        tags = []
        for token in tokens:
            if token == exclude_token:
                continue

            word_def = self.lexicon.get_word_definition(token)
            if not word_def:
                continue
            senses = word_def.get("senses", [])

            if len(senses) == 1:
                constraint = senses[0].get("selectional_constraint")
                if constraint:
                    tags.append(constraint)
        return tags

    # Figurative repair (idiom half only: see core/figurative.py for why).
    def _attach_idiom_meaning(self, logical_form, semantic_payload: Dict[str, Any]) -> None:
        """
        If the parser tagged the predicate as an idiom ("IDIOM:kick_bucket"), attaches its real, NSM-grounded meaning to the payload. This is the one 
        figurative.py mechanism with a clean, unambiguous trigger (the parser's own idiom-gating already confirmed it); metonymic coercion and metaphor 
        mapping need a notion of a predicate's "required argument type" that nothing in the live pipeline computes yet, so they stay standalone for now (see the
        architecture plan's tracking section).
        """
        if not logical_form or not logical_form.predicate.startswith("IDIOM:"):
            return
        idiom_meaning = rewrite_idiom(logical_form.predicate)
        
        if idiom_meaning is not None:
            semantic_payload["idiom_meaning"] = {
                "frame": idiom_meaning.explication.frame.value,
                "slots": idiom_meaning.explication.slots,
            }
