"""
Ties every other module into one coherent turn of conversation: this is where the pieces built and tested standalone across the rest of 
the codebase actually get wired together and run for real.

WHAT PROBLEM THIS FILE SOLVES: Every layer built so far (the lexicon, the grammar, compositional semantics, figurative repair, the
world model, discourse tracking) works correctly on its own: each has its own tests proving that. But a working system isn't just a pile of correct, 
independent pieces; it's those pieces actually calling each other in the right order, on real data, with each one's output feeding the next one's
input. That's this file's entire job, and only this file's job: no new linguistic mechanism gets invented here, only orchestration of mechanisms that 
already exist.

WHAT ONE TURN ACTUALLY DOES, IN ORDER:
    1. Advance the world model's turn clock (so this turn's events get the right relative timing).

    2. Parse the utterance, keeping both the LogicalForm and the derivation tree.

    3. Register any newly-mentioned nouns as discourse referents, using the ORIGINAL (pre-resolution) arguments: a pronoun is never itself a new lexicon noun, 
    so this step naturally never registers a pronoun as if it were a fresh entity.

    4. Resolve every pronoun argument: try cataphora first (forward reference within this sentence, licensed only by Principle C), then fall back to ordinary backward 
    resolution against the world model's active referents, honoring whatever gender/number/animacy the specific pronoun carries.

    5. Check every presupposition trigger word in the utterance against what's already known, accommodating (assuming, and recording) anything genuinely new rather than 
    failing on it.

    6. Disambiguate any polysemous word against its sentence-mates' selectional constraints.

    7. Classify the utterance's speech act, and detect focus if a focus particle is present.

    8. Compile and evaluate truth via SemanticCompiler; if the predicate was idiom-tagged during parsing, look up and attach its real (figurative.py) meaning to the payload.

    9. Record the utterance as an event on the world model's episodic timeline.

    10. Collect any scalar implicatures generated by the words actually used.

    11. If the predicate is a clausal-complement mental-predicate verb (its logical form carries a nested embedded LogicalForm as one of its arguments: core/parser.py's clausal-complement extraction),
    open a Modal & Attitude context for the matrix subject and assert the embedded clause into that context only, never into global reality: this is what keeps "John thinks Mary is home" from corrupting what
    DEMES knows to actually be true.

    12. If a wh-word ("who"/"what") is among the arguments (a non-movement wh-question core/parser.py could actually produce, e.g. "Who walked?" or "What is the suitcase?") push a QUDEntry marking that argument 
    position as the open slot onto this pipeline's persistent QUDStack, so a later bare-fragment answer has something real to fill in.

A COORDINATED sentence ("John left and Mary left") runs every step above uniformly over a list of conjuncts (one conjunct for an ordinary sentence, two for a coordinated one) rather than as a special case bolted 
on afterward: each conjunct gets its own noun registration, pronoun resolution, and truth evaluation, and the coordinator's own connective (AND/OR, from core/parser.py's get_coordinator_connective) combines their 
individual truth values into the turn's overall one.

WHAT THIS FILE DOES NOT DO: It doesn't invoke a language model anywhere: that's interface/neural_bridge.py, not built yet, and nothing here reaches for it as a silent fallback. 
It also doesn't paper over gaps in what the grammar can parse: cataphora resolution, presupposition triggers, and several other mechanisms wired in here will only ever fire on 
the sentence shapes core/parser.py can actually produce today: see the architecture plan's "known partial implementations" section for the current honest list of what that does 
and doesn't cover.
"""

from typing import Dict, Any, List, Optional

from core.types import LogicalForm, ModalFlavor
from core.lexicon import LexiconManager
from core.parser import ChartParser, get_pronoun_features, get_coordinator_connective, get_coordination_conjuncts, WH_WORDS
from core.world_model import WorldModel
from core.world_model import get_presupposition_trigger as _get_presupposition_trigger
from core.semantics import SemanticCompiler
from core.figurative import rewrite_idiom
from core.discourse import (
    classify_speech_act,
    resolve_pronoun_with_agreement,
    attempt_cataphora_resolution,
    find_pronoun_and_name_leaves,
    detect_focus,
    accommodate_presupposition,
    generate_scalar_implicature,
    QUDEntry,
    QUDStack,
)

_PRONOUN_TOKENS = {"it", "he", "him", "she", "her", "they", "them"}

# Which modal flavor a clausal-complement verb opens its attitude-holder's context with: the closed lemma set from the Phase 2.3 design (think/know/believe/realize -> EPISTEMIC, want -> BOULETIC).
_MODAL_FLAVOR_BY_VERB_LEMMA = {
    "think": ModalFlavor.EPISTEMIC,
    "know": ModalFlavor.EPISTEMIC,
    "believe": ModalFlavor.EPISTEMIC,
    "realize": ModalFlavor.EPISTEMIC,
    "want": ModalFlavor.BOULETIC,
}

class DEMESPipeline:
    """
    Coordinates the full symbolic NLU pipeline for one turn of conversation.
    """
    def __init__(self, lexicon_path: str = "data/lexicon.json"):
        self.lexicon = LexiconManager(store_path=lexicon_path)
        self.world_model = WorldModel()
        self.parser = ChartParser(self.lexicon)
        self.compiler = SemanticCompiler(self.world_model, self.lexicon)
        self.qud_stack = QUDStack()

    def process_utterance(self, raw_text: str) -> Dict[str, Any]:
        """
        Runs one complete turn: parse, resolve, accommodate, disambiguate, classify, evaluate, and record. A coordinated sentence's parse comes back as
        a List[LogicalForm] (core/parser.py); an ordinary sentence's comes back as a single LogicalForm (or None). Both are normalized into `conjuncts`
        immediately below (one item for the ordinary case) so every later step (registration, pronoun resolution, evaluation, recording) is written
        once and runs uniformly over however many conjuncts there actually are, rather than as parallel single/coordinated code paths.
        """
        self.world_model.advance_turn()
        tokens = self.parser.tokenize(raw_text)

        parsed_form, derivation_tree = self.parser.parse_with_derivation(raw_text)
        is_coordinated = isinstance(parsed_form, list)
        conjuncts: List[LogicalForm] = parsed_form if is_coordinated else ([parsed_form] if parsed_form else [])
        representative_form = conjuncts[0] if conjuncts else None

        for conjunct in conjuncts:
            self._register_noun_arguments(conjunct)
        cataphora_resolutions = self._resolve_pronoun_arguments(conjuncts, derivation_tree)

        accommodated_presuppositions = self._check_presuppositions(tokens, representative_form)
        word_senses = self._disambiguate_utterance(tokens)
        speech_act = classify_speech_act(representative_form, raw_text)
        focused_constituent = detect_focus(tokens)
        implicatures = [imp for imp in (generate_scalar_implicature(t) for t in tokens) if imp]

        conjunct_payloads = [self.compiler.compile_and_evaluate(conjunct) for conjunct in conjuncts]
        for conjunct, payload in zip(conjuncts, conjunct_payloads):
            self._attach_idiom_meaning(conjunct, payload)
            self.world_model.record_event(conjunct.predicate, roles={}, tense=conjunct.tense)

        modal_context = self._open_modal_attitude_context(representative_form)
        qud_entry = self._update_qud_stack(representative_form)

        if is_coordinated:
            semantic_payload = self._combine_coordinated_payloads(derivation_tree, conjunct_payloads)
            logical_form_out: Any = conjuncts
        else:
            semantic_payload = conjunct_payloads[0] if conjunct_payloads else self.compiler.compile_and_evaluate(None)
            logical_form_out = representative_form

        return {
            "raw_text": raw_text,
            "logical_form": logical_form_out,
            "semantics": semantic_payload,
            "speech_act": speech_act.value,
            "word_senses": word_senses,
            "implicatures": implicatures,
            "accommodated_presuppositions": accommodated_presuppositions,
            "focus": focused_constituent,
            "cataphora_resolutions": cataphora_resolutions,
            "modal_context": modal_context,
            "qud_entry": qud_entry,
        }

    # Coordination: combining a coordinated sentence's per-conjunct payloads into one turn-level result.
    def _combine_coordinated_payloads(self, derivation_tree, conjunct_payloads: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Combines each conjunct's independently-evaluated truth value using the coordinator's own connective (AND requires every conjunct true, OR
        requires at least one): ordinary propositional logic, not a new evaluation mechanism. The truth-value contract (core/semantics.py's
        SemanticCompiler docstring) is preserved: `truth_value` stays a plain bool here too, just computed over several conjuncts instead of one.
        """
        connective = get_coordinator_connective(derivation_tree) or "AND"
        truth_values = [payload.get("truth_value", False) for payload in conjunct_payloads]
        combined_truth = all(truth_values) if connective == "AND" else any(truth_values)
        all_succeeded = all(payload.get("status") == "success" for payload in conjunct_payloads)

        return {
            "status": "success" if all_succeeded else "failure",
            "connective": connective,
            "truth_value": combined_truth if all_succeeded else False,
            "conjuncts": conjunct_payloads,
            "response_intent": "assertion_ack" if (all_succeeded and combined_truth) else "contradiction_notice",
        }

    # Modal & Attitude layer auto-opening.
    def _open_modal_attitude_context(self, logical_form) -> Optional[Dict[str, Any]]:
        """
        If logical_form's predicate is a clausal-complement mental-predicate verb: recognizable purely structurally, by carrying a nested embedded LogicalForm as one of its own arguments 
        (core/parser.py's _extract_clausal_form is the only place that ever produces this shape), opens a Modal & Attitude context (core/world_model.py) for the matrix subject and asserts 
        the embedded clause's own predicate/first-argument into that context alone. This is the actual mechanism that keeps "John thinks Mary is home" from writing "Mary is home" into global 
        reality: the fact lands in John's own epistemic context, isolated from knowledge_base and from every other holder's context. The verb's modal flavor (epistemic vs. bouletic) is looked up by 
        lemma against the small closed table above; a clausal verb whose lemma isn't in that table (there isn't one in the current lexicon, but nothing prevents a future one) simply doesn't open a 
        context, rather than guessing a flavor for it.
        """
        if not logical_form or not logical_form.arguments:
            return None

        embedded_form = next((arg for arg in logical_form.arguments if isinstance(arg, LogicalForm)), None)
        if embedded_form is None or not embedded_form.arguments:
            return None

        verb_lemma = self.lexicon.lemmatize(logical_form.predicate.lower()) or logical_form.predicate.lower()
        modal_flavor = _MODAL_FLAVOR_BY_VERB_LEMMA.get(verb_lemma)
        if modal_flavor is None:
            return None

        holder = str(logical_form.arguments[0])
        context = self.world_model.open_context(holder = holder, modal_flavor = modal_flavor)
        self.world_model.assert_fact_in_context(context.id, embedded_form.predicate, str(embedded_form.arguments[0]))

        return {"context_id": context.id, "holder": holder, "modal_flavor": modal_flavor.value}

    # Question Under Discussion (QUD) stack auto-population.
    def _update_qud_stack(self, logical_form) -> Optional[Dict[str, Any]]:
        """
        If `logical_form` contains a wh-word among its arguments (core/parser.py's WH_WORDS - only the non-movement question patterns the grammar
        actually supports: the wh-word fills an ordinary argument position directly, e.g. "Who walked?" -> arguments ["who"], "What is the suitcase?"
        -> arguments ["what", "suitcase"]), pushes a QUDEntry marking that position as the open slot onto this pipeline's persistent QUDStack. This is
        what makes core/discourse.py's QUDStack, correct and tested standalone since Phase 1, but never populated by any real parse until wh-questions
        existed at all, actually reachable: a later bare-fragment answer can now call self.qud_stack.resolve_fragment(...) against something real. Not
        wired to any caller here yet (fragment answers as their own utterance shape aren't part of this sub-step); this is the population half only.
        """
        if not logical_form or not logical_form.arguments:
            return None

        open_slot_index = next(
            (i for i, argument in enumerate(logical_form.arguments) if isinstance(argument, str) and argument.lower() in WH_WORDS),
            None,
        )
        if open_slot_index is None:
            return None

        entry = QUDEntry(
            predicate = logical_form.predicate,
            arguments = [str(argument) for argument in logical_form.arguments],
            open_slot_index = open_slot_index,
        )
        self.qud_stack.push(entry)

        return {"predicate": entry.predicate, "arguments": entry.arguments, "open_slot_index": entry.open_slot_index}

    # Discourse referents and pronoun resolution.
    def _register_noun_arguments(self, logical_form) -> None:
        """
        Registers any argument that is itself a lexicon noun as a fresh discourse referent, using the arguments
        exactly as the parser produced them: a bare pronoun token like "it" isn't a lexicon entry at all (see core/parser.py's PRONOUNS table),
        so this step naturally never mistakes a pronoun for a new noun mention. An argument the parser flagged as grammatically plural
        (logical_form.plural_arguments) is additionally registered as a plural entity (core/world_model.py's Link's-lattice support) rather
        than an ordinary atomic one: see WorldModel.register_entity's own docstring for the honest limit on what that captures.
        """
        for argument in logical_form.arguments:
            entry = self.lexicon.get_word_definition(str(argument))
            if entry and entry.get("category") == "noun":
                self.world_model.register_referent(str(argument), "noun", properties = [logical_form.predicate.lower()])
                if str(argument) in logical_form.plural_arguments:
                    self.world_model.register_entity(str(argument), kind = str(argument), is_sum = True)

    def _resolve_pronoun_arguments(self, logical_forms: List, derivation_tree) -> List[Dict[str, str]]:
        """
        Resolves every pronoun in `derivation_tree` against `logical_forms` (one form for an ordinary sentence, one per conjunct for a coordinated
        one: see process_utterance). When the tree is a top-level coordination (core/parser.py's get_coordination_conjuncts), each conjunct's own
        subtree is resolved SEPARATELY, matched to its own logical form by position, rather than as one pass over the whole tree: two coordinated
        independent clauses ("It is heavy and John walked") aren't in the kind of subordinate relationship real cataphora requires, so "it" here must
        never be considered a candidate for forward reference to "John" in the other conjunct: only Principle C (not c-commanding) was being checked
        before, which is necessary but not sufficient, and coordination is exactly the sentence shape that exposes the gap between the two. Scoping
        each conjunct to its own subtree closes it structurally, the same "operate over the relevant clause's own subtree, not the whole tree"
        discipline _matrix_clause_leaves already uses for adjuncts.
        """
        conjunct_trees = get_coordination_conjuncts(derivation_tree)
        if conjunct_trees is not None:
            resolutions: List[Dict[str, str]] = []
            for conjunct_tree, logical_form in zip(conjunct_trees, logical_forms):
                resolutions.extend(self._resolve_pronoun_arguments_in_tree([logical_form], conjunct_tree))
            return resolutions

        return self._resolve_pronoun_arguments_in_tree(logical_forms, derivation_tree)

    def _resolve_pronoun_arguments_in_tree(self, logical_forms: List, derivation_tree) -> List[Dict[str, str]]:
        """
        The actual single-tree resolution pass: cataphora first (the more specific, structurally-licensed case), then ordinary backward resolution
        against the world model's active referents as the fallback for whichever pronoun arguments cataphora didn't already resolve. Returns the list
        of cataphoric resolutions actually made, since a resolution for a pronoun inside an excluded adjunct clause ("Before HE entered the room, JOHN
        left": see core/parser.py's _matrix_clause_leaves) can't be recorded by rewriting arguments the way an ordinary in-clause pronoun's is.
        """
        resolutions: List[Dict[str, str]] = []

        if derivation_tree is not None:
            pronoun_leaves, name_leaves = find_pronoun_and_name_leaves(derivation_tree, _PRONOUN_TOKENS, self.lexicon)
            for pronoun_leaf in pronoun_leaves:
                later_names = [leaf for leaf in name_leaves if leaf.span[0] > pronoun_leaf.span[0]]
                resolved = attempt_cataphora_resolution(derivation_tree, pronoun_leaf, later_names)

                if resolved is not None:
                    resolutions.append({"pronoun": pronoun_leaf.token, "resolved_to": resolved.token})
                    for logical_form in logical_forms:
                        logical_form.arguments = [
                            resolved.token if argument == pronoun_leaf.token else argument
                            for argument in logical_form.arguments
                        ]

        for logical_form in logical_forms:
            logical_form.arguments = [
                self._resolve_single_pronoun(str(argument)) if str(argument).lower() in _PRONOUN_TOKENS else argument
                for argument in logical_form.arguments
            ]
        return resolutions

    def _resolve_single_pronoun(self, pronoun_text: str) -> str:
        features = get_pronoun_features(pronoun_text) or {}
        referent = resolve_pronoun_with_agreement(
            self.world_model,
            required_gender = features.get("gender"),
            required_number = features.get("number"),
            required_animate = features.get("animate"),
        )
        return referent.name if referent else pronoun_text

    # Presupposition accommodation.
    def _check_presuppositions(self, tokens: List[str], logical_form) -> List[str]:
        """
        Checks every presupposition-trigger word actually used (matched by lemma, so "stopped" and "stop" both trigger the same check) against what's 
        already known, accommodating anything genuinely new. Returns the list of trigger words that were newly accommodated this turn.
        """
        if not logical_form or not logical_form.arguments:
            return []

        subject = str(logical_form.arguments[0])
        accommodated = []
        for token in tokens:
            lemma = self.lexicon.lemmatize(token) or token

            if _get_presupposition_trigger(lemma) is not None:
                if accommodate_presupposition(self.world_model, lemma, subject):
                    accommodated.append(lemma)
        
        return accommodated

    # Word-sense disambiguation.
    def _disambiguate_utterance(self, tokens: List[str]) -> Dict[str, str]:
        word_senses = {}
        for token in tokens:
            word_def = self.lexicon.get_word_definition(token)

            if word_def and len(word_def.get("senses", [])) > 1:
                argument_types = self._collect_type_tags(tokens, exclude_token = token)
                word_senses[token] = self.lexicon.disambiguate_sense(token, argument_types)

        return word_senses

    def _collect_type_tags(self, tokens: List[str], exclude_token: str) -> List[str]:
        tags = []
        for token in tokens:
            if token == exclude_token:
                continue

            word_def = self.lexicon.get_word_definition(token)
            if not word_def:
                continue
            senses = word_def.get("senses", [])

            if len(senses) == 1:
                constraint = senses[0].get("selectional_constraint")
                if constraint:
                    tags.append(constraint)
        return tags

    # Figurative repair (idiom half only: see core/figurative.py for why).
    def _attach_idiom_meaning(self, logical_form, semantic_payload: Dict[str, Any]) -> None:
        """
        If the parser tagged the predicate as an idiom ("IDIOM:kick_bucket"), attaches its real, NSM-grounded meaning to the payload. This is the one 
        figurative.py mechanism with a clean, unambiguous trigger (the parser's own idiom-gating already confirmed it); metonymic coercion and metaphor 
        mapping need a notion of a predicate's "required argument type" that nothing in the live pipeline computes yet, so they stay standalone for now (see the
        architecture plan's tracking section).
        """
        if not logical_form or not logical_form.predicate.startswith("IDIOM:"):
            return
        idiom_meaning = rewrite_idiom(logical_form.predicate)
        
        if idiom_meaning is not None:
            semantic_payload["idiom_meaning"] = {
                "frame": idiom_meaning.explication.frame.value,
                "slots": idiom_meaning.explication.slots,
            }
