"""
The closed vocabulary of semantic primitives DEMES is allowed to build word meanings out of.

WHAT PROBLEM THIS FILE SOLVES: Earlier versions of DEMES let any word's meaning be described using made-up all-caps labels
(e.g. "portable" was defined using a primitive literally called "MUSHROOM_OR_PORTABLE"). That looks like a principled 
decomposition, but it isn't one: nothing stopped anyone (a person, or later an AI model) from inventing a brand-new label 
every time an existing one didn't quite fit. A vocabulary that can grow without limit isn't really a set of "primitives" at all, 
it's just English words wearing a different font.

HOW THIS FILE FIXES THAT: This file hard-codes a small, fixed list of about 65 concepts, based on decades of cross-linguistic
research (the "Natural Semantic Metalanguage", or NSM, developed by linguists Anna Wierzbicka and Cliff Goddard). The core 
empirical claim behind that research is that every human language has words for these same ~65 ideas (things like DO, HAPPEN, 
THINK, KNOW, WANT, GOOD, BAD, BIG, SMALL, BEFORE, AFTER) and that none of those ~65 ideas can be usefully explained using simpler words. 
They are where definition has to stop. Every other word in the DEMES lexicon (walk, suitcase, portable, heavy, and so on) must 
be defined as some combination of these ~65 primitives and nothing else.

This file is the enforcement point for that rule. It does not try to be clever: it is a fixed list plus a couple of small functions 
that check whether a name is on the list. Every other file in DEMES that wants to accept a new word's definition (whether typed in by a 
person, generated by a language model, or loaded from a JSON file on disk) is expected to run that definition through the checking
functions here first, and reject anything that references a primitive name outside this list. That is what keeps the system's vocabulary 
closed instead of growing without bound.
"""

from typing import Dict, List, Tuple, FrozenSet

# The closed primitive table.

# Each entry maps a category name (used purely for organization and for later layers that need "all the quantifier primitives" or 
# "all the mental-predicate primitives") to the primitive names in that category. The specific English gloss chosen for each primitive 
# (e.g. "SOMETHING" for the NSM prime usually written "something/thing") is just the string identifier DEMES uses internally: 
# it is not itself claimed to be a further decomposition.

# This table is the ONLY place in the entire codebase where a new primitive name should ever be added. If a word's meaning does not fit 
# using what is already here, the word needs to be re-explained in terms of these primitives instead of growing the table: growing this table 
# quietly reintroduces the exact problem ("MUSHROOM_OR_PORTABLE") this file exists to prevent.

_PRIMITIVE_TABLE: Dict[str, Tuple[str, ...]] = {
    "substantives": ("I", "YOU", "SOMEONE", "SOMETHING", "PEOPLE", "BODY"),
    "relational_substantives": ("KIND", "PART"),
    "determiners": ("THIS", "THE_SAME", "OTHER"),
    "quantifiers": ("ONE", "TWO", "SOME", "ALL", "MUCH_MANY", "LITTLE_FEW"),
    "evaluators": ("GOOD", "BAD"),
    "descriptors": ("BIG", "SMALL"),
    "mental_predicates": ("THINK", "KNOW", "WANT", "DONT_WANT", "FEEL", "SEE", "HEAR"),
    "speech": ("SAY", "WORDS", "TRUE"),
    "actions_events_movement_contact": ("DO", "HAPPEN", "MOVE", "TOUCH"),
    "existence_possession": ("BE_SOMEWHERE", "THERE_IS", "HAVE", "BE"),
    "life_and_death": ("LIVE", "DIE"),
    "time": ("WHEN", "NOW", "BEFORE", "AFTER", "A_LONG_TIME", "A_SHORT_TIME", "FOR_SOME_TIME", "MOMENT"),
    "space": ("WHERE", "HERE", "ABOVE", "BELOW", "FAR", "NEAR", "SIDE", "INSIDE", "TOUCHING"),
    "logical_concepts": ("NOT", "MAYBE", "CAN", "BECAUSE", "IF"),
    "intensifiers": ("VERY", "MORE"),
    "similarity": ("LIKE",),
}

# A flat, fast-to-check set of every primitive name across every category. This is what get consulted by is_valid_primitive() below: 
# it's derived automatically from the table above so the two can never drift apart.
ALL_PRIMITIVES: FrozenSet[str] = frozenset(
    name for names in _PRIMITIVE_TABLE.values() for name in names
)

def primitive_categories() -> Tuple[str, ...]:
    """
    Lists the category names the primitive table is organized under (e.g. "quantifiers", "mental_predicates"). Later layers that only care
    about one kind of primitive (for example, Cooper storage only needing the quantifier primitives) use this together with primitives_in_category()
    instead of filtering the full list by hand.
    """
    return tuple(_PRIMITIVE_TABLE.keys())


def primitives_in_category(category: str) -> Tuple[str, ...]:
    """
    Returns every primitive name that belongs to the given category, or an empty tuple if the category name isn't recognized.
    """
    return _PRIMITIVE_TABLE.get(category, ())


def is_valid_primitive(name: str) -> bool:
    """
    Answers the one question this whole file exists to answer: is this name one of the ~65 closed primitives, or did someone (a person, a language
    model, a bug) just make it up? Comparison is exact and case-sensitive: primitive names are always written in full uppercase with underscores,
    the same convention already used throughout the lexicon.
    """
    return name in ALL_PRIMITIVES


def validate_primitives(primitives: List[Dict]) -> List[str]:
    """
    Checks a list of primitive entries in the shape used throughout the lexicon (each entry a dict with at least a "name" key, e.g.
    {"name": "MOVE", "category": "action"}) and reports which ones are not members of the closed vocabulary.

    Returns an empty list if every entry is valid. Returns the list of offending names otherwise, so a caller (typically LexiconManager) can
    either reject the whole definition or surface a clear, specific error instead of silently accepting an invented primitive.
    """
    invalid_names = []
    for entry in primitives:
        name = entry.get("name")
        if not is_valid_primitive(name):
            invalid_names.append(name)

    return invalid_names


class InvalidPrimitiveError(ValueError):
    """
    Raised when code that needs a hard failure (rather than just a list of problems back from validate_primitives) encounters a primitive name
    outside the closed vocabulary.
    """
    pass # There is no additional implementation necessary to declare a custom error exception in Python.

def assert_valid_primitives(primitives: List[Dict]) -> None:
    """
    Same check as validate_primitives(), but raises InvalidPrimitiveError immediately instead of returning a list: useful at the exact point
    where a new lexicon entry is about to be written to disk, where "silently continue with a bad definition" is not an acceptable outcome.
    """
    invalid_names = validate_primitives(primitives)
    if invalid_names:
        raise InvalidPrimitiveError(
            f"Not part of the closed NSM primitive vocabulary: {invalid_names}."
            f"Re-explain this meaning using existing primitives instead of adding new ones."
        )